### ISSUE TITLE
F16v4 freezing on startup 

### ISSUE THREAD

**Issue by Robwar23** [Pixelcontroller/f16v4_issues#32]
Hi, 

Recently received a new f16v4, all started well and have had it working with Xlights. 

Over the last couple of days on startup it has frozen on falcon logo failing to connect to its static up, the only way I could get it to work was to do a factory reset. This is my first time with a falcon so I may be doing something wrong, but would appreciate some help or advice 
It’s on build 22. 
Many thanks

**Comment by dpitts** [comment]
HI

Build 22 has been pulled. Please reload 21 and do a factory reset.

Thank you,

David Pitts
***@***.***

From: Robwar23 ***@***.***>
Sent: Wednesday, November 2, 2022 5:27 PM
To: dpitts/f16v4_issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dpitts/f16v4_issues] F16v4 freezing on startup (Issue #32)


Hi,

Recently received a new f16v4, all started well and have had it working with Xlights.

Over the last couple of days on startup it has frozen on falcon logo failing to connect to its static up, the only way I could get it to work was to do a factory reset. This is my first time with a falcon so I may be doing something wrong, but would appreciate some help or advice
It’s on build 22.
Many thanks
