### ISSUE TITLE
f48v4 null pixels

### ISSUE THREAD

**Issue by koolsb** [Pixelcontroller/f16v4_issues#34]
I have several strings on different ports of my f48v4 with multiple null pixels....i.e.

Port 1: Prop (48) - Null (2) - Prop 2 (48) Null (2) - Prop 3 (48)

The null pixels are correctly being left off, however, in this example, prop 3 is not lighting the last 4 pixels. It appears that channel data is sent for 144 pixels, when in fact it should be sending for 148. I'm running build 22 and am having xlights upload the output config. This appears in test mode run directly from the f48v4. 

I have mitigated the issue by creating a "fake" single line model of 4 pixels and assigning it after Prop 3. This is not a show stopper but an issue I wanted to share.

**Comment by Poporacer** [comment]
Can you check this using Build 25? I think it might be fixed.

**Comment by keithsw1111** [comment]
Closing as no response and we believe this is long fixed.
