### ISSUE TITLE
F48V4 Firmware 21 Load Settings fail

### ISSUE THREAD

**Issue by Poporacer** [Pixelcontroller/f16v4_issues#35]
If you have a certain number of Universes and channels defined in the F48V4 and try to load a configuration, it will fail. (I am not sure of the threshold that causes this.) In order to load the settings, I had to set the inputs to 1 universe and then clear the pixel ports and then the load settings would work.
[Falcon_F48V4_119.zip](https://github.com/dpitts/f16v4_issues/files/10096791/Falcon_F48V4_119.zip)

**Comment by keithsw1111** [comment]
I cant test this until I get back to Oz.

**Comment by Poporacer** [comment]
Fixed in Build 25 beta-Thanks!
