### ISSUE TITLE
Freezing in Player Standalone with .21

### ISSUE THREAD

**Issue by derwin12** [Pixelcontroller/f16v4_issues#38]
From zoom - not much to go on but putting it here for awareness. The log didnt show much but the scenario is a standalone setup with a couple megatrees. No internet, using RTC. It would play thru the sequences (2 or 3) multiple times then when he came back the next night it would need a power cycle to boot. No crash or anything obvious in the logs - just saying it was playing a sequence and couldnt reach time.google.com and it was doing some RTC catchups.

Again .. not much .. but putting it here for awareness.  Xlights v.19   F16V4 v.21.

**Comment by TrekErs** [comment]
[Falcon_F16V4_C59C log.txt](https://github.com/dpitts/f16v4_issues/files/10128105/Falcon_F16V4_C59C.log.txt)

**Comment by derwin12** [comment]
Closing as outdated..
