### ISSUE TITLE
Problem of upgrading in all versions

### ISSUE THREAD

**Issue by ScarpelliniStefano96** [Pixelcontroller/f16v4_issues#44]
Hi.
I received from a store a f16v4. When I first turned it on I turned it on with ethernet and connected. I set up wifi and it gave me an ip address. But when I connect I get "Error Page (ESP) 004". I then, on the advice of a person in a forum, tried updating the firmware to version 26 via the web interface. At startup, bootloader v1.02 16 appears, then loads CPU1, CPU2 and then writes starting and the Falcon logo appears and stays still. I tried with the SD to put version 21 (as it was originally): it copied my files, it does the same process but the screen remains black and does nothing else. I try also with version 3. Is there anything I can do?
i also take a dat file, if it is helping you.[https://drive.google.com/file/d/1qjkBX6WYbW_s5G647eLmeCmHTgPJKfMC/view?usp=sharing](url)

**Comment by keithsw1111** [comment]
Build 21 is likely not compatible with your board. Over time there are small variations between boards such that more recent boards need the latest firmware to even function at all. That would explain the black screen.

If it gets stuck at the logo on boot do the power on again and hold down the select button. This should clear any corrupt settings.

**Comment by ScarpelliniStefano96** [comment]
Tomorrow i try. If select doesn't work?

Stefano

Il dom 20 ago 2023, 20:01 Keith Westley ***@***.***> ha
scritto:

**Comment by ScarpelliniStefano96** [comment]
When i receive it the build id is 21, i remember. Tomorrow i try to do the sel pression like you tell me. If it doesn't work?

**Comment by ScarpelliniStefano96** [comment]
Hi. One news: i contacted the store where i bought the f16v4 and he tell me
that the build installed is 27. Where can i find It?

Stefano

Il dom 20 ago 2023, 20:35 Stefano Scarpellini <
***@***.***> ha scritto:

**Comment by keithsw1111** [comment]
I uploaded it into this github earlier today.

**Comment by keithsw1111** [comment]
Did it work?

**Comment by ScarpelliniStefano96** [comment]
It works. Thanks.

Stefano

Il ven 25 ago 2023, 11:45 Keith Westley ***@***.***> ha
scritto:

**Comment by ScarpelliniStefano96** [comment]
Hi.
After 3 years since I got this f16v4, I'm still running the same operating system. Is it worth updating, and if so, which version? I don't want to run into issues updating and have to jump through hoops to revert back. ;)

What can i do?

**Comment by keithsw1111** [comment]
In general we do not recommend updating unless you are encountering issues and even then looking through the release notes before updating as we would only recommend upgrading if there seems to be a fix for the issue are having. If you cant see a fix then contact us about your issue and we will endeavour to reproduce and send you a fix.

**Comment by ScarpelliniStefano96** [comment]
Ok, thanks
