### ISSUE TITLE
f16v4 out of the box will not boot up, no OLED

### ISSUE THREAD

**Issue by Xmouse55** [Pixelcontroller/f16v4_issues#45]
I have checked all wiring,and voltage to the board. all the fuses are lit, but the OLED is not active, and pushing buttons render no response.

**Comment by dpitts** [comment]
This is not a firmware issue.

**Comment by Xmouse55** [comment]
Hi David, I compared this one to our other controller and discovered the slide switch on the lower left was in the wrong position. It booted right up after that. 

I have 2 identical controllers, yet this newest one boots differently, and I’m thinking this might be a setting.

When the CPU boots, I get the blue flashing LED on both, but then the newer one has a red led that comes on, and stays on. Maybe something to do with WIFI? I can connect to the ethernet, and all is working well in that regard. The controller seems perfectly fine, but could you tell me what the red led under the blue one means?

Thank you for responding.

 

Peter Mulberger

President

The Pinetree Group L.L.C.

301 N 15th St. Colorado Springs, CO 80904

719-332-0022
