### ISSUE TITLE
Feature Request: Test Page to include CMY

### ISSUE THREAD

**Issue by mjunek** [Pixelcontroller/f16v4_issues#47]
Currently the pixel test page has got a bunch of options for testing pixels, all of which are very handy in their respective situations.

One I find quite handy to run is a CMY test- this is great for determining if particular pixel is having colour issues.

The reasoning here is the eye will visually see a different colour much easier than a missing colour. eg: In a sea of red, you wont notice one red LED out, but in a sea of magenta, you'll clearly see the one blue LED that's missing its red colour.

So the request here is to include a CMY colour wash in the same way there is an RGB colour wash in the v4 (and possibly v5) firmware.

Cheers 
 M.

**Comment by keithsw1111** [comment]
A CMY like RGB will be in an upcoming build. CMY colour wash is less practical.
