### ISSUE TITLE
F16v4 Will not update from Build32 to Build33

### ISSUE THREAD

**Issue by JonD24** [Pixelcontroller/f16v4_issues#54]
Multiple F16v4 controllers will not update from build 32 to build 33 using UI interface.  FPP Proxy, no FPP proxy, after power cycle, all the same.  Indicator bar almost instantly goes from 0 to 33% and hangs.  Will eventually display error message that the upload timed out.

UPDATE:  I was able to upgrade all of them using the SD Card method.  (I do leave a SD card in each controller with showlogo.jpg full-time if that makes a difference.)

**Comment by keithsw1111** [comment]
Were you trying to update over wired ethernet or over wifi?

**Comment by JonD24** [comment]
Did not try to remove the SD card before trying to upgrade from the UI.  The SD cards are empty other than the showlogo.jpg file.  I played with the remote player feature a while back, but did not end up using it.  Did not have a use for the SD Card and left the logo there. 

I am beyond this issue, so feel free to close if no one else is reporting the same.

**Comment by keithsw1111** [comment]
I will close ... no one has reported issues loading over a wired connection and build 33 has a fix for people having issues over wifi.
