### ISSUE TITLE
Updating from Build 21 - 33 or 35: WebUI not functional, cant re-flash

### ISSUE THREAD

**Issue by taylorbird** [Pixelcontroller/f16v4_issues#56]
Flashed to Build 35 tonight (From 21) on a v4-16 tonight via the web file upload method.  Everything appeared to work but after post-update reboot, the webui will not funciton.  It will load the site, and pop the "retriving configuration ..." but never move past.   I tried to reflash with SD method but the board does not see the card. Ive tried 3 diff SD cards and 2 diff builds, the controller never acknowledges the card.  Ive rebooted, power cycled, ensured no backfeed power from power injection, and held select to clear settings during boot.

Core controller functions work, but unable to edit anyting, so adding props/configuring pixels/etc ... dead in the water for setting up my show this year.

 Chrome inspect tab shows some JS errors

cntrl.js is reporting
{"R":200,"T":"Q","F":1,"B":0,"M":"ST","RB":0,"P":{"NT":"time.google.com","TZ":0,"DST":"N","IN":"Y","U":319,"N":"Falcon_F16V4_3E40","O":0,"BR":16,"V":"F16V4 Bld 35","FW":35,"WI":"10.58.0.1","WK":"255.255.255.0","WG":"0.0.0.0","WD":"0.0.0.0","WSD":"D","HS":"Y","WE":"Y","WS":"","WP":"","CP":"","TS":0,"TG":"255.255.255.255","DP":10000,"CS":0,"CE":7979,"TL":0,"ML":0,"FT":25,"E10":"N","DL":3,"sm":0,"su":1,"ssc":0,"sr":250000,"T1":248,"T2":273,"V1":48,"V2":52,"PT":391,"FN":1500,"UC":16,"C":"02-fe-00-2e-00-17","P":16,"S":1,"A":1,"B":0,"UG":{"s":""},"SU":"N","SD":"D","I":"10.33.103.100","K":"255.255.255.0","G":"10.33.103.1","D":"10.33.103.1","DM":0,"RI":0,"SY":"N","PR":"N","Z":65535,"BT":5,"ps":0,"LV":1,"FS":40,"BS":75,"DT":"2024-12-07","TM":"06:52:22","CC":255,"WT":0,"BS1":100,"BS2":100,"BS3":100,"NW":0,"TA":0,"FH":0,"EL":5,"WL":90,"SRU":0,"DTP":10,},"W":" ","L":""}

but then
VM41:1 Uncaught SyntaxError: Expected double-quoted property name in JSON at position 853 (line 1 column 854)
    at JSON.parse (<anonymous>)
    at handleHTTPMessage (cntrlr_35.js:1:21947)
    at http.onload (cntrlr_35.js:1:10470)
    
    sendMessage Q ST
cntrlr_35.js:1 {"T":"Q","M":"ST","B":0,"E":0,"I":0,"P":{}}
cntrlr_35.js:1 Request for status sent.

and it just loops.

No config pages are usable.

**Comment by taylorbird** [comment]
was able to click around enough to get settings to load and re-flash with Build 33.  However, same behavior persists ... its almost like it cant load from some segment of the board

**Comment by taylorbird** [comment]
And to add ... ports directly connected to the controller are functioning as before update, responding properly to FPP, etc. Smart receiver chains are no longer responding even though they are power cycled and connected

**Comment by keithsw1111** [comment]
Hang on … I see the problem … 36 will be up in the next hour

From: taylorbird ***@***.***>
Sent: Saturday, 7 December 2024 5:55 PM
To: Pixelcontroller/f16v4_issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pixelcontroller/f16v4_issues] Build 35: WebUI not functional, cant re-flash (Issue #56)


Flashed to Build 35 tonight (From 21) on a v4-16 tonight via the web file upload method. Everything appeared to work but after post-update reboot, the webui will not funciton. It will load the site, and pop the "retriving configuration ..." but never move past. I tried to reflash with SD method but the board does not see the card. Ive tried 3 diff SD cards and 2 diff builds, the controller never acknowledges the card. Ive rebooted, power cycled, ensured no backfeed power from power injection, and held select to clear settings during boot.

Core controller functions work, but unable to edit anyting, so adding props/configuring pixels/etc ... dead in the water for setting up my show this year.

Chrome inspect tab shows some JS errors

cntrl.js is reporting
{"R":200,"T":"Q","F":1,"B":0,"M":"ST","RB":0,"P":{"NT":"time.google.com","TZ":0,"DST":"N","IN":"Y","U":319,"N":"Falcon_F16V4_3E40","O":0,"BR":16,"V":"F16V4 Bld 35","FW":35,"WI":"10.58.0.1","WK":"255.255.255.0","WG":"0.0.0.0","WD":"0.0.0.0","WSD":"D","HS":"Y","WE":"Y","WS":"","WP":"","CP":"","TS":0,"TG":"255.255.255.255","DP":10000,"CS":0,"CE":7979,"TL":0,"ML":0,"FT":25,"E10":"N","DL":3,"sm":0,"su":1,"ssc":0,"sr":250000,"T1":248,"T2":273,"V1":48,"V2":52,"PT":391,"FN":1500,"UC":16,"C":"02-fe-00-2e-00-17","P":16,"S":1,"A":1,"B":0,"UG":{"s":""},"SU":"N","SD":"D","I":"10.33.103.100","K":"255.255.255.0","G":"10.33.103.1","D":"10.33.103.1","DM":0,"RI":0,"SY":"N","PR":"N","Z":65535,"BT":5,"ps":0,"LV":1,"FS":40,"BS":75,"DT":"2024-12-07","TM":"06:52:22","CC":255,"WT":0,"BS1":100,"BS2":100,"BS3":100,"NW":0,"TA":0,"FH":0,"EL":5,"WL":90,"SRU":0,"DTP":10,},"W":" ","L":""}

but then
VM41:1 Uncaught SyntaxError: Expected double-quoted property name in JSON at position 853 (line 1 column 854)
at JSON.parse ()
at handleHTTPMessage (cntrlr_35.js:1:21947)
at http.onload (cntrlr_35.js:1:10470)

sendMessage Q ST

cntrlr_35.js:1 {"T":"Q","M":"ST","B":0,"E":0,"I":0,"P":{}}
cntrlr_35.js:1 Request for status sent.

and it just loops.

No config pages are usable.

**Comment by keithsw1111** [comment]
Yeah build 35 is bad for V4 board. Suggest you drop back to 34. I will have 36 up shortly. I have pulled it down from the repo.

**Comment by keithsw1111** [comment]
Build 36 is up which addresses this issue.

**Comment by taylorbird** [comment]
confirmed, backgrading to 34 resolved and reupdating to 36 no longer displays the issue, thanks!
